#!/usr/bin/env python3
"""Build the minimal quest plugin that hosts AgencyEngine's SkyUI MCM script.

The file keeps its .esp extension but carries the TES4 ESL flag. Its only new
record is already in the legacy-safe 0x800-0xFFF light-plugin range. Skyrim VR
loads it through SkyrimVRESL; the DLL never looks up or stores the quest FormID.
It has only Skyrim.esm as a master, so missing SkyUI disables the attached
script without preventing AgencyEngine from loading.
"""

import argparse
import struct
from pathlib import Path

FORM_ID_QUEST = 0x01000800
NEXT_OBJECT_ID = 0x801
HEADER_TAIL = bytes.fromhex("000000002c000000")
FLAG_ESL = 0x00000200
SCRIPT_NAME = "AgencyEngine_MCM"


def zstring(text: str) -> bytes:
    return text.encode("cp1252") + b"\x00"


def subrecord(signature: str, data: bytes) -> bytes:
    if len(signature) != 4:
        raise ValueError(f"invalid subrecord signature: {signature!r}")
    if len(data) > 0xFFFF:
        raise ValueError(f"{signature} is too large for a subrecord")
    return signature.encode("ascii") + struct.pack("<H", len(data)) + data


def record(signature: str, form_id: int, subrecords: list[bytes], flags: int = 0) -> bytes:
    body = b"".join(subrecords)
    header = signature.encode("ascii") + struct.pack("<III", len(body), flags, form_id)
    return header + HEADER_TAIL + body


def top_group(label: str, records: list[bytes]) -> bytes:
    body = b"".join(records)
    return b"GRUP" + struct.pack("<I", 24 + len(body)) + label.encode("ascii") + struct.pack("<i", 0) + HEADER_TAIL + body


def script_binding(script_name: str) -> bytes:
    name = script_name.encode("cp1252")
    body = struct.pack("<hhH", 5, 2, 1)
    body += struct.pack("<H", len(name)) + name
    body += struct.pack("<BH", 0, 0)  # local script, no properties
    return subrecord("VMAD", body)


def build_plugin() -> bytes:
    local_quest_id = FORM_ID_QUEST & 0x00FFFFFF
    if not 0x800 <= local_quest_id <= 0xFFF:
        raise ValueError("the MCM quest FormID is outside the legacy ESL range")

    # Start Game Enabled + Run Once. The quest remains active; Run Once only
    # prevents another start after it has already initialized its MCM script.
    quest_data = struct.pack("<HBBiI", 0x0111, 0, 0xFF, 0, 0)
    quest = record(
        "QUST",
        FORM_ID_QUEST,
        [
            subrecord("EDID", zstring("AgencyEngineMCMQuest")),
            script_binding(SCRIPT_NAME),
            subrecord("DNAM", quest_data),
            subrecord("NEXT", b""),
            subrecord("ANAM", struct.pack("<I", 0)),
        ],
    )
    quest_group = top_group("QUST", [quest])

    header = record(
        "TES4",
        0,
        [
            subrecord("HEDR", struct.pack("<fiI", 1.70, 2, NEXT_OBJECT_ID)),
            subrecord("CNAM", zstring("cleanestpoison")),
            subrecord("SNAM", zstring("Hosts AgencyEngine's optional SkyUI Mod Configuration Menu.")),
            subrecord("MAST", zstring("Skyrim.esm")),
            subrecord("DATA", struct.pack("<Q", 0)),
            subrecord("INTV", struct.pack("<I", 1)),
        ],
        flags=FLAG_ESL,
    )
    return header + quest_group


def main() -> int:
    default_output = Path(__file__).resolve().parents[1] / "statics" / "AgencyEngine.esp"
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=default_output)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in plugin differs from generated bytes")
    args = parser.parse_args()

    generated = build_plugin()
    if SCRIPT_NAME.encode("ascii") not in generated or b"QUST" not in generated:
        raise RuntimeError("generated plugin is missing its quest or VMAD script binding")

    if args.check:
        if not args.output.exists():
            raise SystemExit(f"missing generated plugin: {args.output}")
        if args.output.read_bytes() != generated:
            raise SystemExit(f"{args.output} is stale; run {Path(__file__).name}")
        print(f"verified {args.output} ({len(generated)} bytes)")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated)
    print(f"wrote {args.output} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
